name: Playwright Tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env.test file
        run: |
          echo "🔧 Creating .env.test file..."
          echo "🔧 Available secrets check:"
          echo "SUPABASE_URL: ${{ secrets.SUPABASE_URL != '' && 'SET' || 'NOT SET' }}"
          echo "SUPABASE_KEY: ${{ secrets.SUPABASE_KEY != '' && 'SET' || 'NOT SET' }}"
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env.test
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env.test
          echo "NODE_ENV=test" >> .env.test
          echo "TEST_USER_EMAIL=test@example.com" >> .env.test
          echo "TEST_USER_PASSWORD=testpassword123" >> .env.test
          echo "ADMIN_USER_EMAIL=admin@example.com" >> .env.test
          echo "ADMIN_USER_PASSWORD=adminpassword123" >> .env.test
          echo "🔧 Contents of .env.test:"
          cat .env.test

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run Playwright tests
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-results
          path: e2e/results/
          retention-days: 30
